// Generated by IB v0.3.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface DetailController: UIViewController

@property IBOutlet UIBarButtonItem * button;



-(IBAction) toggleColorAction:(id) sender;

@end



